"""
Datenpipeline für CodeLM Pre-Training
Lädt, filtert, dedupliziert und tokenisiert Code-Daten.

Schritte:
  1. Download von HuggingFace Datasets (The Stack v2, StarCoder Data)
  2. Qualitätsfilterung
  3. Deduplizierung (MinHash LSH)
  4. Tokenisierung + Speicherung als .bin Dateien (Memory-mapped)

Verwendung:
    # Schritt 1: Daten herunterladen und filtern
    python data_pipeline.py download --output_dir ./data/raw --languages python javascript typescript rust

    # Schritt 2: Tokenisieren
    python data_pipeline.py tokenize --raw_dir ./data/raw --output_dir ./data/tokenized --tokenizer_dir ./tokenizer

    # Schritt 3: Statistiken
    python data_pipeline.py stats --data_dir ./data/tokenized
"""

import os
import re
import json
import struct
import hashlib
import argparse
import numpy as np
from pathlib import Path
from typing import Iterator, Optional
from dataclasses import dataclass, field
from multiprocessing import Pool, cpu_count


# ---------------------------------------------------------------------------
# Konfiguration
# ---------------------------------------------------------------------------

@dataclass
class PipelineConfig:
    # Qualitätsfilter
    min_chars: int = 100
    max_chars: int = 500_000
    max_non_ascii_ratio: float = 0.3
    max_line_length: int = 1000       # Zeilen länger als das → wahrscheinlich minified
    min_lines: int = 3
    max_avg_line_length: float = 200  # Durchschnittliche Zeilenlänge

    # Deduplizierung
    dedup_enabled: bool = True
    minhash_num_perm: int = 128       # Mehr = genauer, aber langsamer
    jaccard_threshold: float = 0.8    # Ähnlichkeit ab der dedupliziert wird

    # Tokenisierung
    max_seq_len: int = 1024           # Tokens pro Sequenz (für Training)
    fim_rate: float = 0.5             # 50% der Sequenzen als FIM formatieren

    # Unterstützte Sprachen (Priorität)
    languages: list = field(default_factory=lambda: [
        "python", "javascript", "typescript", "rust",
        "go", "java", "cpp", "c", "csharp",
        "html", "css", "sql", "shell",
    ])

    # HuggingFace Datasets
    datasets: list = field(default_factory=lambda: [
        {
            "name": "bigcode/the-stack-v2-dedup",
            "split": "train",
            "text_field": "content",
            "lang_field": "lang",
            "max_samples_per_lang": 500_000,
        },
        {
            "name": "bigcode/starcoderdata",
            "split": "train",
            "text_field": "content",
            "lang_field": "lang",
            "max_samples_per_lang": 200_000,
        },
    ])


# ---------------------------------------------------------------------------
# Qualitätsfilter
# ---------------------------------------------------------------------------

class QualityFilter:
    def __init__(self, config: PipelineConfig):
        self.config = config

        # Regex für häufige Müll-Muster
        self._auto_generated = re.compile(
            r"(auto.?generated|do not edit|generated by|this file was generated)",
            re.IGNORECASE
        )
        self._minified = re.compile(r"^.{500,}$", re.MULTILINE)

    def is_valid(self, text: str, lang: str = None) -> tuple[bool, str]:
        """
        Prüft ob ein Code-Snippet qualitativ hochwertig ist.
        Returns: (is_valid, reason_if_invalid)
        """
        # Länge
        if len(text) < self.config.min_chars:
            return False, "zu_kurz"
        if len(text) > self.config.max_chars:
            return False, "zu_lang"

        # Zeilen
        lines = text.splitlines()
        if len(lines) < self.config.min_lines:
            return False, "zu_wenig_zeilen"

        # Durchschnittliche Zeilenlänge (Minified Code erkennen)
        avg_line_len = sum(len(l) for l in lines) / len(lines)
        if avg_line_len > self.config.max_avg_line_length:
            return False, "minified"

        # Sehr lange Einzelzeilen
        max_line = max(len(l) for l in lines)
        if max_line > self.config.max_line_length:
            return False, "zeile_zu_lang"

        # Non-ASCII Ratio
        non_ascii = sum(1 for c in text if ord(c) > 127)
        if non_ascii / len(text) > self.config.max_non_ascii_ratio:
            return False, "zu_viel_non_ascii"

        # Auto-generierter Code (oft wenig Lernwert)
        if self._auto_generated.search(text[:500]):
            return False, "auto_generiert"

        return True, ""

    def filter_batch(self, samples: list[dict]) -> list[dict]:
        """Filtert einen Batch von Samples."""
        valid = []
        stats = {}
        for sample in samples:
            text = sample.get("content", sample.get("text", ""))
            lang = sample.get("lang", "")
            ok, reason = self.is_valid(text, lang)
            if ok:
                valid.append(sample)
            else:
                stats[reason] = stats.get(reason, 0) + 1
        return valid, stats


# ---------------------------------------------------------------------------
# MinHash Deduplizierung
# ---------------------------------------------------------------------------

class MinHashDeduplicator:
    """
    Einfache MinHash-basierte Deduplizierung.
    Für große Datensätze: datasketch Library verwenden.
    """

    def __init__(self, num_perm: int = 128, threshold: float = 0.8):
        self.num_perm = num_perm
        self.threshold = threshold
        self.seen_hashes: set = set()

        # Zufällige Hash-Parameter (a, b für ax+b mod p)
        import random
        rng = random.Random(42)
        self._a = [rng.randint(1, (1 << 31) - 1) for _ in range(num_perm)]
        self._b = [rng.randint(0, (1 << 31) - 1) for _ in range(num_perm)]
        self._p = (1 << 31) - 1  # Mersenne Prime

    def _shingles(self, text: str, k: int = 5) -> set[int]:
        """Erstellt k-Gramm Shingles aus dem Text."""
        # Normalisierung: Whitespace kollabieren
        text = re.sub(r'\s+', ' ', text.lower())
        shingles = set()
        for i in range(len(text) - k + 1):
            shingle = text[i:i+k]
            shingles.add(hash(shingle) & 0xFFFFFFFF)
        return shingles

    def _minhash(self, shingles: set[int]) -> tuple[int, ...]:
        """Berechnet MinHash Signatur."""
        if not shingles:
            return tuple([0] * self.num_perm)
        sig = []
        for i in range(self.num_perm):
            min_val = min(
                (self._a[i] * s + self._b[i]) % self._p
                for s in shingles
            )
            sig.append(min_val)
        return tuple(sig)

    def _signature_hash(self, sig: tuple) -> str:
        """Kompakter Hash der Signatur für schnellen Lookup."""
        # Nur erste 32 Werte für Geschwindigkeit
        return hashlib.md5(str(sig[:32]).encode()).hexdigest()

    def is_duplicate(self, text: str) -> bool:
        """Prüft ob ein Text ein Duplikat ist."""
        shingles = self._shingles(text)
        sig = self._minhash(shingles)
        sig_hash = self._signature_hash(sig)

        if sig_hash in self.seen_hashes:
            return True

        self.seen_hashes.add(sig_hash)
        return False

    def deduplicate(self, texts: list[str]) -> list[bool]:
        """Gibt für jeden Text zurück ob er behalten werden soll."""
        return [not self.is_duplicate(t) for t in texts]


# ---------------------------------------------------------------------------
# FIM (Fill-in-the-Middle) Transformation
# ---------------------------------------------------------------------------

def apply_fim(tokens: list[int], fim_pre_id: int, fim_suf_id: int, fim_mid_id: int,
              eos_id: int, rng=None) -> list[int]:
    """
    Transformiert eine Token-Sequenz in FIM-Format.
    Wählt zufällig einen Split-Punkt und formatiert als:
    [fim_pre] prefix [fim_suf] suffix [fim_mid] middle [eos]
    """
    import random
    if rng is None:
        rng = random.Random()

    n = len(tokens)
    if n < 10:
        return tokens

    # Zufällige Split-Punkte
    split1 = rng.randint(1, n - 2)
    split2 = rng.randint(split1 + 1, n - 1)

    prefix = tokens[:split1]
    middle = tokens[split1:split2]
    suffix = tokens[split2:]

    # FIM Format: prefix → suffix → middle (PSM Format, wie in StarCoder)
    return [fim_pre_id] + prefix + [fim_suf_id] + suffix + [fim_mid_id] + middle + [eos_id]


# ---------------------------------------------------------------------------
# Tokenisierung + Speicherung
# ---------------------------------------------------------------------------

class TokenizedDataset:
    """
    Speichert tokenisierte Daten als Memory-mapped Binary Files.
    Format: uint16 Arrays (reicht für vocab_size <= 65535)
    """

    def __init__(self, output_dir: str, split: str = "train"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.split = split
        self.shard_size = 100_000_000  # 100M Tokens pro Shard
        self.current_shard = 0
        self.current_tokens = []
        self.total_tokens = 0
        self.total_docs = 0

    def add_tokens(self, tokens: list[int]):
        """Fügt Token-IDs hinzu."""
        self.current_tokens.extend(tokens)
        self.total_tokens += len(tokens)
        self.total_docs += 1

        if len(self.current_tokens) >= self.shard_size:
            self._flush_shard()

    def _flush_shard(self):
        """Schreibt aktuellen Shard auf Disk."""
        if not self.current_tokens:
            return

        shard_path = self.output_dir / f"{self.split}_{self.current_shard:04d}.bin"
        arr = np.array(self.current_tokens, dtype=np.uint16)
        arr.tofile(shard_path)

        print(f"Shard {self.current_shard} gespeichert: {len(self.current_tokens):,} tokens → {shard_path}")
        self.current_shard += 1
        self.current_tokens = []

    def finalize(self):
        """Schreibt letzten Shard und Metadaten."""
        self._flush_shard()

        # Metadaten speichern
        meta = {
            "total_tokens": self.total_tokens,
            "total_docs": self.total_docs,
            "num_shards": self.current_shard,
            "shard_size": self.shard_size,
            "dtype": "uint16",
            "split": self.split,
        }
        meta_path = self.output_dir / f"{self.split}_meta.json"
        with open(meta_path, "w") as f:
            json.dump(meta, f, indent=2)

        print(f"\nDataset finalisiert:")
        print(f"  Tokens gesamt:  {self.total_tokens:,}")
        print(f"  Dokumente:      {self.total_docs:,}")
        print(f"  Shards:         {self.current_shard}")
        print(f"  Metadaten:      {meta_path}")


class MemoryMappedDataset:
    """
    Lädt tokenisierte Daten als Memory-mapped Arrays für effizientes Training.
    """

    def __init__(self, data_dir: str, split: str = "train", seq_len: int = 1024):
        self.data_dir = Path(data_dir)
        self.split = split
        self.seq_len = seq_len

        # Metadaten laden
        meta_path = self.data_dir / f"{split}_meta.json"
        with open(meta_path) as f:
            self.meta = json.load(f)

        # Alle Shards laden
        self.shards = []
        for i in range(self.meta["num_shards"]):
            shard_path = self.data_dir / f"{split}_{i:04d}.bin"
            arr = np.memmap(shard_path, dtype=np.uint16, mode="r")
            self.shards.append(arr)

        self.total_tokens = self.meta["total_tokens"]
        self.num_sequences = self.total_tokens // seq_len

        print(f"Dataset geladen: {self.total_tokens:,} tokens, {self.num_sequences:,} Sequenzen")

    def __len__(self) -> int:
        return self.num_sequences

    def __getitem__(self, idx: int) -> dict:
        """Gibt eine Sequenz zurück."""
        # Globaler Token-Offset
        start = idx * self.seq_len
        end = start + self.seq_len + 1  # +1 für Labels

        # Shard und lokalen Offset berechnen
        shard_size = len(self.shards[0])
        shard_idx = start // shard_size
        local_start = start % shard_size

        # Tokens aus Shard lesen
        shard = self.shards[min(shard_idx, len(self.shards) - 1)]
        tokens = shard[local_start:local_start + self.seq_len + 1].astype(np.int64)

        # Padding falls nötig
        if len(tokens) < self.seq_len + 1:
            tokens = np.pad(tokens, (0, self.seq_len + 1 - len(tokens)))

        import torch
        x = torch.from_numpy(tokens[:-1].copy())
        y = torch.from_numpy(tokens[1:].copy())
        return {"input_ids": x, "labels": y}

    def get_dataloader(self, batch_size: int, shuffle: bool = True, num_workers: int = 4):
        """Erstellt einen DataLoader."""
        from torch.utils.data import DataLoader
        return DataLoader(
            self,
            batch_size=batch_size,
            shuffle=shuffle,
            num_workers=num_workers,
            pin_memory=True,
        )


# ---------------------------------------------------------------------------
# Download & Verarbeitung
# ---------------------------------------------------------------------------

def download_and_process(
    output_dir: str,
    tokenizer_dir: str,
    config: PipelineConfig,
    max_samples: int = None,
):
    """
    Hauptfunktion: Lädt Daten von HuggingFace, filtert und tokenisiert sie.
    """
    from datasets import load_dataset
    from tokenizer_train import CodeTokenizer
    import random

    rng = random.Random(42)
    tokenizer = CodeTokenizer(tokenizer_dir)
    quality_filter = QualityFilter(config)
    deduplicator = MinHashDeduplicator(
        num_perm=config.minhash_num_perm,
        threshold=config.jaccard_threshold,
    ) if config.dedup_enabled else None

    dataset_writer = TokenizedDataset(output_dir, split="train")

    total_processed = 0
    total_kept = 0
    filter_stats = {}

    for ds_config in config.datasets:
        print(f"\nLade Dataset: {ds_config['name']}")

        for lang in config.languages:
            print(f"  Sprache: {lang}")
            try:
                # Dataset laden (streaming für große Datensätze)
                ds = load_dataset(
                    ds_config["name"],
                    data_dir=f"data/{lang}",
                    split=ds_config["split"],
                    streaming=True,
                    trust_remote_code=True,
                )
            except Exception as e:
                print(f"    Fehler beim Laden: {e}")
                continue

            lang_count = 0
            max_per_lang = ds_config.get("max_samples_per_lang", 500_000)
            if max_samples:
                max_per_lang = min(max_per_lang, max_samples)

            for sample in ds:
                if lang_count >= max_per_lang:
                    break

                text = sample.get(ds_config["text_field"], "")
                if not text:
                    continue

                total_processed += 1

                # Qualitätsfilter
                ok, reason = quality_filter.is_valid(text, lang)
                if not ok:
                    filter_stats[reason] = filter_stats.get(reason, 0) + 1
                    continue

                # Deduplizierung
                if deduplicator and deduplicator.is_duplicate(text):
                    filter_stats["duplikat"] = filter_stats.get("duplikat", 0) + 1
                    continue

                # Tokenisieren
                filename = sample.get("max_stars_repo_path", f"file.{lang}")
                tokens = tokenizer.encode_file(text, filename=filename)

                # FIM Transformation (50% der Sequenzen)
                if rng.random() < config.fim_rate and len(tokens) > 20:
                    tokens = apply_fim(
                        tokens,
                        tokenizer.fim_pre,
                        tokenizer.fim_suf,
                        tokenizer.fim_mid,
                        tokenizer.eos_id,
                        rng=rng,
                    )

                # In Chunks aufteilen (max_seq_len)
                for i in range(0, len(tokens), config.max_seq_len):
                    chunk = tokens[i:i + config.max_seq_len]
                    if len(chunk) >= 64:  # Zu kurze Chunks überspringen
                        dataset_writer.add_tokens(chunk)

                total_kept += 1
                lang_count += 1

                if total_processed % 10_000 == 0:
                    ratio = total_kept / total_processed * 100
                    print(f"    Verarbeitet: {total_processed:,} | Behalten: {total_kept:,} ({ratio:.1f}%)")

    dataset_writer.finalize()

    print(f"\nFilter-Statistiken:")
    for reason, count in sorted(filter_stats.items(), key=lambda x: -x[1]):
        print(f"  {reason}: {count:,}")

    print(f"\nGesamt: {total_processed:,} verarbeitet, {total_kept:,} behalten ({total_kept/total_processed*100:.1f}%)")


# ---------------------------------------------------------------------------
# Statistiken
# ---------------------------------------------------------------------------

def print_stats(data_dir: str):
    """Gibt Statistiken über ein tokenisiertes Dataset aus."""
    data_path = Path(data_dir)

    for split in ["train", "val"]:
        meta_path = data_path / f"{split}_meta.json"
        if not meta_path.exists():
            continue

        with open(meta_path) as f:
            meta = json.load(f)

        tokens = meta["total_tokens"]
        docs = meta["total_docs"]
        shards = meta["num_shards"]
        size_gb = tokens * 2 / 1e9  # uint16 = 2 bytes

        print(f"\n{split.upper()} Split:")
        print(f"  Tokens:    {tokens:,} ({tokens/1e9:.2f}B)")
        print(f"  Dokumente: {docs:,}")
        print(f"  Shards:    {shards}")
        print(f"  Größe:     {size_gb:.2f} GB")
        print(f"  Avg Tokens/Doc: {tokens/docs:.0f}")

        # Trainingszeit schätzen (RTX 4070 Ti)
        # ~50K tokens/sec bei batch=4, seq=1024
        tokens_per_sec = 50_000
        hours = tokens / tokens_per_sec / 3600
        print(f"  Geschätzte Trainingszeit (4070 Ti): {hours:.0f}h ({hours/24:.1f} Tage)")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="CodeLM Datenpipeline")
    subparsers = parser.add_subparsers(dest="command")

    # Download & Verarbeitung
    dl_parser = subparsers.add_parser("process", help="Daten laden, filtern und tokenisieren")
    dl_parser.add_argument("--output_dir", type=str, required=True)
    dl_parser.add_argument("--tokenizer_dir", type=str, required=True)
    dl_parser.add_argument("--languages", nargs="+", default=None)
    dl_parser.add_argument("--max_samples", type=int, default=None, help="Max Samples (für Tests)")
    dl_parser.add_argument("--no_dedup", action="store_true", help="Deduplizierung deaktivieren")
    dl_parser.add_argument("--fim_rate", type=float, default=0.5)

    # Statistiken
    stats_parser = subparsers.add_parser("stats", help="Dataset-Statistiken anzeigen")
    stats_parser.add_argument("--data_dir", type=str, required=True)

    args = parser.parse_args()

    if args.command == "process":
        config = PipelineConfig()
        if args.languages:
            config.languages = args.languages
        if args.no_dedup:
            config.dedup_enabled = False
        config.fim_rate = args.fim_rate

        download_and_process(
            output_dir=args.output_dir,
            tokenizer_dir=args.tokenizer_dir,
            config=config,
            max_samples=args.max_samples,
        )

    elif args.command == "stats":
        print_stats(args.data_dir)

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
